import { v4 as uuidv4} from 'uuid';

/**
 * Generates a unique session ID
 * 
 * The session ID is generated using UUID version 4. If a pin is provided,
 * it is prefixed to the session ID, separated by a hyphen. 
 * 
 * @param {string} pin - An optional pin to be included in the session ID. 
 * @returns {string} - The generated session ID, optionally prefixed with the provided pin.
 */
export function generateSessionId(pin?: string) : string {
    // Generate a UUID v4
    let sessionId = uuidv4();

    // If a pin is provided, prefix it to the session ID
    if (pin){
        sessionId = `${pin}-${sessionId}`;
    }

    return sessionId;
}

/**
 * Generates a random pin. 
 * 
 * The pin is a random alphanumeric string of length 6, generated by taking 
 * a substring of a randomly generated string.
 * 
 * @returns {string} - the generated random pin.  
 */
export function generateRandomPin(): string {
    // Generate a random alphanumeric string and take a substring of length 6
    let pin = Math.random().toString(36).substring(2, 8);
    return pin;
}

