version: "3.8"

services: 
  mongo: 
    image: mongo:4.4
    restart: always
    container_name: mongo-next
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user1234